[package]
name = "diffview"
version = "0.1.0"
edition.workspace = true
publish.workspace = true

[dependencies]
ropey.workspace = true
similar.workspace = true

[dev-dependencies]
anyhow.workspace = true
