[package]
name = "gpui-manos-plate"
version = "0.1.0"
publish = false
edition.workspace = true

[lib]
doctest = false

[dependencies]
gpui.workspace = true
ropey.workspace = true
serde.workspace = true
sum-tree.workspace = true

[dev-dependencies]
serde_json.workspace = true
