[package]
name = "gpui-manos-plate"
version = "0.1.0"
publish = false
edition.workspace = true

[lib]
doctest = false

[dependencies]
gpui.workspace = true
gpui-component.workspace = true
gpui-plate-core.workspace = true
serde.workspace = true
serde_json.workspace = true
